export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const DELETE_USER = "DELETE_USER";
export const SAVE_USER = "SAVE_USER";
export const ADD_USER = "ADD_USER";

export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
